---
- name: My playbook
  hosts: localhost
  become: true
  vars_files: 
    - "vars.yml"

  tasks:
    - name: Install required system packages
      package:
        name:
          - git
        state: latest

    - name: Install git
      include_role:
        name: git

    - name: "Install Docker [Ubuntu]"
      include_role:
        name: docker

    - name: Install SSHD
      include_role:
        name: willshersystems.sshd

    - name: Install Visual Studio Code
      include_role:
        name: gantsign.visual-studio-code 
      vars:
        users:
          - username: "{{ unix_username }}"
