---
- name: My playbook
  hosts: localhost
  become: true
  vars_files:
    - "vars.yml"

  tasks:
    - name: Install required system packages
      package:
        name:
          - git
        state: latest

    - name: "Set git user config"
      include_role:
        name: gantsign.git_user
      vars:
        users:
          - username: "{{ unix_username }}"
            git_user_name: "{{ git_user_name }}"
            git_user_email: "{{ git_user_email }}"
            git_user_force: "{{ git_user_force }}"

    - name: "Install Docker"
      include_role:
        name: geerlingguy.docker
      vars:
        docker_users: ["{{ unix_username }}"]

    - name: Install SSHD
      include_role:
        name: willshersystems.sshd

    - name: Install Visual Studio Code
      include_role:
        name: gantsign.visual-studio-code
      vars:
        users:
          - username: "{{ unix_username }}"
