- name: Check if chezmoi is already installed
  ansible.builtin.command: chezmoi --version
  register: chezmoi_installed
  ignore_errors: true
  changed_when: false

- name: Install Chezmoi
  when: not chezmoi_installed
  shell: "sh -c \"$(curl -fsLS get.chezmoi.io)\" -- -b $HOME/.local/bin"

- name: Initialize Chezmoi
  shell: "chezmoi init --apply --verbose git@github.com:{{ github_user }}/dotfiles.git"

