- name: "Set git user config"
  include_role:
    name: gantsign.git_user
  vars:
    users:
      - username: "{{ unix_username }}"
        git_user_name: "{{ git_user_name }}"
        git_user_email: "{{ git_user_email }}"
        git_user_force: "{{ git_user_force }}"
