- name: "[Ubuntu] Install Docker system packages"
  package:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: latest

- name: "[Ubuntu] Add Docker GPG apt key"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: "[Ubuntu] Add Docker repository"
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: "[Ubuntu] Install Docker"
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest

- name: Create Docker group
  group:
    name: docker
    state: present

- name: Add user to Docker group
  user:
    name: "{{ unix_username }}"
    groups: docker
    append: yes

- name: Verify Docker service is running
  service:
    name: docker
    state: started
    enabled: yes
